protocol_mapping:
    bedstat: bedstat

pipelines:
  bedstat:
    name: BEDSTAT
    path: pipeline/bedstat.py
    looper_args: True
    arguments:
      "--bedfile": output_file_path
      "--genome": genome
      "--sample-yaml": yaml_file
